model:
  preproc: True
  num_output_layers: 2
  num_input_layers: 1
  
closure_test:
  fit_level: 2

training:
  optimizer: "Adam"
  range_alpha: 5
  range_beta: 20
  range_gamma: 100
  lag_mult_pos: 0.001
  lag_mult_int: 0.001
  x_int: [0.001,0.98]

dataset:
  observable: "Eh"
  filename_data: "FASERv_Run3_EPOS+POWHEG_7TeV_events_comb_min_20_events"
  filename_stat_error: "FASERv_Run3_EPOS+POWHEG_7TeV_stat_error_comb_min_20_events"
  filename_sys_error: "FASERv_Run3_EPOS+POWHEG_7TeV_sys_error_comb_min_20_events"
  filename_cov_matrix: "FASERv_Run3_EPOS+POWHEG_7TeV_cov_matrix_comb_min_20_events"
  filename_binning: "FK_Eh_binsize_nub_min_20_events"
  grid_node: 'x_alpha.dat'
  pdf: "FASERv_Run3_EPOS+POWHEG_7TeV"
  pdf_set: 2
  fit_faser_data: False
  
postfit:
  particle_id_nu: 14
  particle_id_nub: -14

hyperopt_params:
  act_functions: ["relu", "softplus", "tanh", "sigmoid"]
  lower_max_num_epochs: 1500
  upper_max_num_epochs: 50000
  min_num_layers: 2
  max_num_layers: 10
  min_num_nodes: 2
  max_num_nodes: 20
  min_wd: .000001
  max_wd: .1
  min_lr: 0.0001
  max_lr: 0.1
  min_patience: 1
  max_patience: 10000
  num_folds: 2

