rm __pycache__/read_faserv_pdf.cpython-312.pyc
rm 	new_faserv2/fit_sibyll/El_fit/chi_square.txt
rm 	new_faserv2/fit_sibyll/El_fit/chi_squares_for_postfit.txt
rm 	new_faserv2/fit_sibyll/El_fit/events.txt
rm 	new_faserv2/fit_sibyll/El_fit/pdf.txt
rm 	new_faserv2/fit_sibyll/El_fit/postfit_analysis.py
rm 	new_faserv2/fit_sibyll/El_fit/pred.txt
rm 	new_faserv2/fit_sibyll/El_fit/runscripts/scripts.txt
rm 	new_faserv2/fit_sibyll/El_fit/train_indices.txt
rm 	new_faserv2/fit_sibyll/El_fit/training_lengths.txt
rm 	new_faserv2/fit_sibyll/El_fit/val_indices.txt
rm 	read_faserv_pdf.py
