rm events_mu.txt
rm events_mub.txt
rm pred.txt
rm chi_square.txt
rm chi_squares_for_postfit.txt
rm mu_pdf.txt
rm mub_pdf.txt
rm train_indices.txt
rm training_lengths.txt
rm val_indices.txt
rm fit_report_El.txt
