rm events.txt
rm events_mub.txt
rm pred.txt
rm chi_square.txt
rm chi_squares_for_postfit.txt
rm pdf.txt
rm mub_pdf.txt
rm train_indices.txt
rm training_lengths.txt
rm val_indices.txt
rm fit_report_dpm_theta.txt
